"""Create Users Table

Revision ID: 7b773d42c9f7
Revises:
Create Date: 2025-02-03 08:56:49.254981

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from app.enums.user import RoleEnum, VerifyStatusEnum

# revision identifiers, used by Alembic.
revision: str = "7b773d42c9f7"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# ENUM型の定義
role_enum = RoleEnum.sa_enum_type()
verify_status_enum = VerifyStatusEnum.sa_enum_type()


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # ENUM型を作成
    role_enum.create(op.get_bind(), checkfirst=True)
    verify_status_enum.create(op.get_bind(), checkfirst=True)
    
    op.create_table(
        "users",
        sa.Column(
            "id",
            sa.BIGINT(),
            nullable=False,
            primary_key=True,
            comment="ID",
        ),
        sa.Column(
            "name",
            sa.String(length=256),
            nullable=False,
            comment="名前"
        ),
        sa.Column(
            "email",
            sa.String(length=256),
            nullable=False,
            comment="メールアドレス",
        ),
        sa.Column(
            "role",
            role_enum,
            nullable=False,
            comment="権限",
        ),
        sa.Column(
            "password",
            sa.String(length=256),
            nullable=False,
            comment="パスワード",
        ),
        sa.Column(
            "verify_status",
            verify_status_enum,
            server_default="unverified",
            nullable=False,
            comment="認証ステータス",
        ),
        sa.Column(
            "reset_password_token",
            sa.String(length=768),
            nullable=True,
            comment="パスワード再設定トークン",
        ),
        sa.Column(
            "reset_password_expires",
            sa.Integer,
            nullable=True,
            comment="パスワード再設定有効期限",
        ),
        sa.Column(
            "invite_token",
            sa.String(length=768),
            nullable=True,
            comment="招待トークン"
        ),
        sa.Column(
            "invite_expires",
            sa.Integer,
            nullable=True,
            comment="招待有効期限",
        ),
        sa.Column(
            "last_login_at",
            sa.TIMESTAMP(timezone=True),
            nullable=True,
            comment="最終ログイン日時",
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="作成日時",
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="更新日時",
        ),
        sa.Column(
            "deleted_at",
            sa.TIMESTAMP(timezone=True),
            nullable=True,
            comment="削除日時",
        ),
        sa.UniqueConstraint("email"),
        comment="ユーザー",
    )

    # インデックス
    op.create_index("idx_users_name", "users", ["name"], unique=False)
    op.create_index(
        "idx_users_email_active",
        "users",
        ["email"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL")
    )
    op.create_index("idx_users_role", "users", ["role"], unique=False)
    op.create_index("idx_users_verify_status", "users", ["verify_status"], unique=False)
    op.create_index("idx_users_deleted_at", "users", ["deleted_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_users_name", table_name="users")
    op.drop_index("idx_users_email_active", table_name="users")
    op.drop_index("idx_users_role", table_name="users")
    op.drop_index("idx_users_verify_status", table_name="users")
    op.drop_index("idx_users_deleted_at", table_name="users")
    op.drop_table("users")
    
    # ENUM型を削除
    role_enum.drop(op.get_bind(), checkfirst=True)
    verify_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
